global:
  working_dir: .
  env:
    RUST_LOG: info
  log:
    file: logs/app.log
    level: debug
    max_size: 200
    max_files: 10

processes:
  web:
    name: web
    program: python
    args: ["examples/simple_web.py"]
    working_dir: .
    auto_restart: true
    start_delay: 5
    max_restarts: 3
    health_check_url: http://localhost:5000/health
    log:
      file: logs/web.log
      level: info
      max_size: 100
      max_files: 5 